package com.chargingstation.csbe.domain.utils;

import java.util.HashMap;
import java.util.Map;

public class CommonCodeMapper {
    private static final Map<String, String> BUSI_ID_MAP = new HashMap<>();
    private static final Map<String, String> CHARGER_STATUS_MAP = new HashMap<>();
    private static final Map<String, String> CHARGER_TYPE_MAP = new HashMap<>();
    private static final Map<String, String> REGION_MAP = new HashMap<>();

    static {
        BUSI_ID_MAP.put("AC", "아우토크립트");
        BUSI_ID_MAP.put("AE", "한국자동차환경협회");
        BUSI_ID_MAP.put("AH", "미항");
        BUSI_ID_MAP.put("AL", "이콘");
        BUSI_ID_MAP.put("AM", "아마노코리아");
        BUSI_ID_MAP.put("AP", "애플망고");
        BUSI_ID_MAP.put("BA", "부안군");
        BUSI_ID_MAP.put("BE", "브라이트에너지파트너스");
        BUSI_ID_MAP.put("BG", "비지니스");
        BUSI_ID_MAP.put("BK", "비케이에너지");
        BUSI_ID_MAP.put("BN", "블루네트웍스");
        BUSI_ID_MAP.put("BP", "지커넥트");
        BUSI_ID_MAP.put("BS", "복산나이스");
        BUSI_ID_MAP.put("BT", "보타리에너지");
        BUSI_ID_MAP.put("CA", "이브이시스");
        BUSI_ID_MAP.put("CB", "지엘비이원");
        BUSI_ID_MAP.put("CC", "코콤");
        BUSI_ID_MAP.put("CG", "서울씨엔지");
        BUSI_ID_MAP.put("CH", "채움모빌리티");
        BUSI_ID_MAP.put("CI", "클린이");
        BUSI_ID_MAP.put("CN", "씨앤모빌리티");
        BUSI_ID_MAP.put("CO", "환경계획이엔지");
        BUSI_ID_MAP.put("CP", "캐스트프로");
        BUSI_ID_MAP.put("CR", "크로커스");
        BUSI_ID_MAP.put("CS", "한국EV충전서비스센터");
        BUSI_ID_MAP.put("CT", "씨티카");
        BUSI_ID_MAP.put("CU", "씨어스");
        BUSI_ID_MAP.put("CV", "체바");
        BUSI_ID_MAP.put("DC", "대성물류건설");
        BUSI_ID_MAP.put("DE", "대구공공시설관리공단");
        BUSI_ID_MAP.put("DG", "대구광역시");
        BUSI_ID_MAP.put("DL", "딜라이브");
        BUSI_ID_MAP.put("DO", "대한송유관공사");
        BUSI_ID_MAP.put("DP", "데우플러스");
        BUSI_ID_MAP.put("DR", "도로스코피이엔지");
        BUSI_ID_MAP.put("DS", "대신");
        BUSI_ID_MAP.put("DY", "동양이엔피");
        BUSI_ID_MAP.put("E0", "에너지플러스");
        BUSI_ID_MAP.put("EA", "에베");
        BUSI_ID_MAP.put("EB", "일렉트리");
        BUSI_ID_MAP.put("EC", "이지차저");
        BUSI_ID_MAP.put("EE", "이마트");
        BUSI_ID_MAP.put("EG", "에너지홀딩스");
        BUSI_ID_MAP.put("EH", "이피티");
        BUSI_ID_MAP.put("EK", "이노케미텍");
        BUSI_ID_MAP.put("EL", "엘란비탈");
        BUSI_ID_MAP.put("EM", "evmost");
        BUSI_ID_MAP.put("EN", "이엔");
        BUSI_ID_MAP.put("EO", "E1");
        BUSI_ID_MAP.put("EP", "이브이플러그");
        BUSI_ID_MAP.put("ER", "이엘일렉트릭");
        BUSI_ID_MAP.put("ES", "태스");
        BUSI_ID_MAP.put("ET", "이시티");
        BUSI_ID_MAP.put("EV", "에버온");
        BUSI_ID_MAP.put("EX", "한국도로공사");
        BUSI_ID_MAP.put("EZ", "차차인");
        BUSI_ID_MAP.put("FE", "에프이씨");
        BUSI_ID_MAP.put("FT", "포티투닷");
        BUSI_ID_MAP.put("G1", "광주시");
        BUSI_ID_MAP.put("G2", "광주시");
        BUSI_ID_MAP.put("GD", "그린포트");
        BUSI_ID_MAP.put("GE", "그린전력");
        BUSI_ID_MAP.put("GG", "강진군");
        BUSI_ID_MAP.put("GN", "지커넥트");
        BUSI_ID_MAP.put("GO", "유한회사 골드에너지");
        BUSI_ID_MAP.put("GP", "군포시");
        BUSI_ID_MAP.put("GR", "그리드위즈");
        BUSI_ID_MAP.put("GS", "GS칼텍스");
        BUSI_ID_MAP.put("HB", "에이치비이엔지");
        BUSI_ID_MAP.put("HD", "현대자동차");
        BUSI_ID_MAP.put("HE", "한국전기차충전서비스");
        BUSI_ID_MAP.put("HJ", "한전");
        BUSI_ID_MAP.put("HL", "에이치엘비이원");
        BUSI_ID_MAP.put("HM", "휴맥스이브이");
        BUSI_ID_MAP.put("HP", "해피차저");
        BUSI_ID_MAP.put("HR", "한국홈충전");
        BUSI_ID_MAP.put("HR", "한국전기차충전");
        BUSI_ID_MAP.put("HS", "홈앤서비스");
        BUSI_ID_MAP.put("HU", "환경서비스");
        BUSI_ID_MAP.put("HW", "한화솔루션");
        BUSI_ID_MAP.put("HY", "현대엔지니어링");
        BUSI_ID_MAP.put("IC", "인천국제공항공사");
        BUSI_ID_MAP.put("IK", "익산시");
        BUSI_ID_MAP.put("IM", "아이마켓코리아");
        BUSI_ID_MAP.put("IN", "신세계아이앤씨");
        BUSI_ID_MAP.put("IO", "아이온커뮤니케이션즈");
        BUSI_ID_MAP.put("IV", "인큐버스");
        BUSI_ID_MAP.put("JA", "이브이시스");
        BUSI_ID_MAP.put("JC", "제주에너지공사");
        BUSI_ID_MAP.put("JD", "제주특별자치도");
        BUSI_ID_MAP.put("JE", "제주전기자동차서비스");
        BUSI_ID_MAP.put("JH", "종합하이이엔씨");
        BUSI_ID_MAP.put("JJ", "전주시");
        BUSI_ID_MAP.put("JN", "제이미니에프앤");
        BUSI_ID_MAP.put("JT", "제주테크노파크");
        BUSI_ID_MAP.put("JU", "정읍시");
        BUSI_ID_MAP.put("KA", "기아자동차");
        BUSI_ID_MAP.put("KC", "한국컴퓨터");
        BUSI_ID_MAP.put("KE", "한국전기차인프라기술");
        BUSI_ID_MAP.put("KG", "KG에너지");
        BUSI_ID_MAP.put("KH", "김해시");
        BUSI_ID_MAP.put("KI", "기아자동차");
        BUSI_ID_MAP.put("KJ", "순천시");
        BUSI_ID_MAP.put("KL", "클린일렉스");
        BUSI_ID_MAP.put("KM", "카카오모빌리티");
        BUSI_ID_MAP.put("KN", "한국환경공단");
        BUSI_ID_MAP.put("KO", "이브이파킹서비스");
        BUSI_ID_MAP.put("KP", "한국전력공사");
        BUSI_ID_MAP.put("KR", "이브이씨코리아");
        BUSI_ID_MAP.put("KS", "한국전기차솔루션");
        BUSI_ID_MAP.put("KT", "KT");
        BUSI_ID_MAP.put("KU", "한국충전연합");
        BUSI_ID_MAP.put("L3", "엘쓰리일렉트릭파워");
        BUSI_ID_MAP.put("LA", "에스에이텍");
        BUSI_ID_MAP.put("LC", "롯데건설");
        BUSI_ID_MAP.put("LD", "롯데이노베이트");
        BUSI_ID_MAP.put("LH", "LG유플러스 볼트업(플러그인)");
        BUSI_ID_MAP.put("LK", "엘에스링크");
        BUSI_ID_MAP.put("LT", "금성계전기");
        BUSI_ID_MAP.put("LU", "LG유플러스 볼트업");
        BUSI_ID_MAP.put("MA", "맥퍼스");
        BUSI_ID_MAP.put("ME", "기후에너지환경부");
        BUSI_ID_MAP.put("MI", "모니트");
        BUSI_ID_MAP.put("MO", "매니지온");
        BUSI_ID_MAP.put("MR", "미래씨앤알");
        BUSI_ID_MAP.put("MS", "미래에스디");
        BUSI_ID_MAP.put("MT", "모던텍");
        BUSI_ID_MAP.put("MV", "메가볼트");
        BUSI_ID_MAP.put("NB", "엔비플러스");
        BUSI_ID_MAP.put("NE", "에너넷");
        BUSI_ID_MAP.put("NH", "농협경제지주 신재생에너지센터");
        BUSI_ID_MAP.put("NI", "나주시");
        BUSI_ID_MAP.put("NN", "이브이네스트");
        BUSI_ID_MAP.put("NS", "뉴맥스플랜");
        BUSI_ID_MAP.put("NT", "NICE인프라");
        BUSI_ID_MAP.put("NX", "넥씽");
        BUSI_ID_MAP.put("OB", "현대오일뱅크");
        BUSI_ID_MAP.put("OS", "온스테이션");
        BUSI_ID_MAP.put("PA", "이브이파킹");
        BUSI_ID_MAP.put("PC", "아이파킹");
        BUSI_ID_MAP.put("PE", "피앤이시스템즈");
        BUSI_ID_MAP.put("PI", "GS차차비");
        BUSI_ID_MAP.put("PK", "핌프킨");
        BUSI_ID_MAP.put("PL", "플러그링크");
        BUSI_ID_MAP.put("PM", "피라미드모터스");
        BUSI_ID_MAP.put("PS", "이브이파킹서비스");
        BUSI_ID_MAP.put("PW", "파워큐브");
        BUSI_ID_MAP.put("RE", "레드이앤지");
        BUSI_ID_MAP.put("RS", "리셀파워");
        BUSI_ID_MAP.put("S1", "이브이에스피피");
        BUSI_ID_MAP.put("SA", "설악에너텍");
        BUSI_ID_MAP.put("SB", "소프트베리");
        BUSI_ID_MAP.put("SC", "삼척시");
        BUSI_ID_MAP.put("SD", "스칼라데이터");
        BUSI_ID_MAP.put("SE", "서울시");
        BUSI_ID_MAP.put("SF", "스타코프");
        BUSI_ID_MAP.put("SF", "스타코프");
        BUSI_ID_MAP.put("SG", "SK시그넷");
        BUSI_ID_MAP.put("SH", "에스메이지에너지");
        BUSI_ID_MAP.put("SJ", "세종시");
        BUSI_ID_MAP.put("SK", "SK에너지");
        BUSI_ID_MAP.put("SL", "에스에스기전");
        BUSI_ID_MAP.put("SM", "성민기업");
        BUSI_ID_MAP.put("SN", "서울에너지공사");
        BUSI_ID_MAP.put("SO", "선광시스템");
        BUSI_ID_MAP.put("SP", "스마트푸드테크놀로지");
        BUSI_ID_MAP.put("SR", "SK렌터카");
        BUSI_ID_MAP.put("SS", "루이스이브이씨");
        BUSI_ID_MAP.put("ST", "SK일렉링크");
        BUSI_ID_MAP.put("SU", "순천시 체육시설관리소");
        BUSI_ID_MAP.put("SZ", "SG생활안전");
        BUSI_ID_MAP.put("TB", "태백시청");
        BUSI_ID_MAP.put("TD", "타디스테크놀로지");
        BUSI_ID_MAP.put("TE", "테슬라");
        BUSI_ID_MAP.put("TH", "태현교통");
        BUSI_ID_MAP.put("TL", "티엘컴퍼니");
        BUSI_ID_MAP.put("TM", "티맵");
        BUSI_ID_MAP.put("TR", "한마음장애인복지회");
        BUSI_ID_MAP.put("TS", "태성코텍");
        BUSI_ID_MAP.put("TU", "티비유");
        BUSI_ID_MAP.put("TV", "마이로브");
        BUSI_ID_MAP.put("UN", "유니이브이");
        BUSI_ID_MAP.put("UP", "유플러스아이티");
        BUSI_ID_MAP.put("US", "울산시");
        BUSI_ID_MAP.put("VT", "볼타");
        BUSI_ID_MAP.put("WB", "이브이루키");
        BUSI_ID_MAP.put("WJ", "우진산전");
        BUSI_ID_MAP.put("YC", "노란충전");
        BUSI_ID_MAP.put("YY", "양양군");
        BUSI_ID_MAP.put("ZE", "이브이모드코리아");
        BUSI_ID_MAP.put("ZP", "지풍파워");

        CHARGER_STATUS_MAP.put("0", "알수없음");
        CHARGER_STATUS_MAP.put("1", "통신이상");
        CHARGER_STATUS_MAP.put("2", "사용가능");
        CHARGER_STATUS_MAP.put("3", "충전중");
        CHARGER_STATUS_MAP.put("4", "운영중지");
        CHARGER_STATUS_MAP.put("5", "점검중");

        CHARGER_TYPE_MAP.put("01", "DC차데모");
        CHARGER_TYPE_MAP.put("02", "AC완속");
        CHARGER_TYPE_MAP.put("03", "DC차데모+AC3상");
        CHARGER_TYPE_MAP.put("04", "DC콤보");
        CHARGER_TYPE_MAP.put("05", "DC차데모+DC콤보");
        CHARGER_TYPE_MAP.put("06", "DC차데모+AC3상+DC콤보");
        CHARGER_TYPE_MAP.put("07", "AC3상");
        CHARGER_TYPE_MAP.put("08", "DC콤보(완속)");
        CHARGER_TYPE_MAP.put("09", "NACS");
        CHARGER_TYPE_MAP.put("10", "DC콤보+NACS");
        CHARGER_TYPE_MAP.put("11", "DC콤보 2(버스전용)");

        REGION_MAP.put("11", "서울특별시");
        REGION_MAP.put("26", "부산광역시");
        REGION_MAP.put("27", "대구광역시");
        REGION_MAP.put("28", "인천광역시");
        REGION_MAP.put("29", "광주광역시");
        REGION_MAP.put("30", "대전광역시");
        REGION_MAP.put("31", "울산광역시");
        REGION_MAP.put("36", "세종특별자치시");
        REGION_MAP.put("41", "경기도");
        REGION_MAP.put("43", "충청북도");
        REGION_MAP.put("44", "충청남도");
        REGION_MAP.put("46", "전라남도");
        REGION_MAP.put("47", "경상북도");
        REGION_MAP.put("48", "경상남도");
        REGION_MAP.put("50", "제주특별자치도");
        REGION_MAP.put("51", "강원특별자치도");
        REGION_MAP.put("52", "전북특별자치도");
    }

    public static String getBusiNm(String busiId, String defaultNm) {
        return BUSI_ID_MAP.getOrDefault(busiId, defaultNm);
    }

    public static String getChargerStatusNm(String stat) {
        return CHARGER_STATUS_MAP.getOrDefault(stat, "상태미확인");
    }

    public static String getChargerTypeNm(String type) {
        return CHARGER_TYPE_MAP.getOrDefault(type, "기타");
    }

    public static Map<String, String> getRegionMap() {
        return new HashMap<>(REGION_MAP);
    }
}
